### ISSUE TITLE
RICHIESTA DI MODIFICA URGENTE A CODESTO REPOSITORY

### ISSUE THREAD

**Issue by Pako3549** [antomaiett4/FoodGuard#1]
Buonasera egregio @antomaiett4 ,
vorrei farle notare che questo repository è organizzato **malissimo**, ha solo un README.md (scritto pure in maniera tutt'altro che eccellente) e manca del tutto di immagini esplicative e video.
Mi costringe a convocare il **sommo** per farlo intervenire sulla questione.
Firmato,
Pako3549 
P.S: in allegato trova un'immagine che descrive il mio stato d'animo corrente.

![Gestione-della-rabbia](https://github.com/antomaiett4/FoodGuard/assets/62575316/ef85aa57-878e-43ac-b6f8-a2cc6911305e)

**Comment by clibroia** [comment]
Ahi, quanto a dir la bruttura e la sciatteria di uno statement senza punto
e virgola è nulla confrontato al desolante abbandono di questo raccoglitore
digitale di speranze e conoscenze, meglio denominata repository.
Con questa io diffido dal perseverare nell'offesa ai sani principi di una
regolare ed estatica cura dei codici e dei manualetti operativi,
volgarmente detti documentazioni.
Possano il full-stack, la data science e la devops infondere la giusta guida
Meditate
